name: sast-tools

on:
  push:
    branches:
      - main
  workflow_dispatch: 

permissions:
  contents: read

jobs:
  bearer:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Run Report
        id: report
        uses: bearer/bearer-action@v2
        with: 
          exit-code: 0
  poutine:
    runs-on: ubuntu-latest
    permissions:
      security-events: write
      contents: read
    steps:
      - name: poutine - GitHub Actions SAST
        uses: boostsecurityio/poutine-action@main
        with:
          output_file: results.sarif
      - name: Inspect SARIF JSON
        run: cat results.sarif
  vorpal:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Vorpal Github Action With reviewdog
        uses: Checkmarx/vorpal-reviewdog-github-action@v1.2.0
        with:
          source_path: src/mcp_atlassian
          filter_mode: file
          github_token: ${{ secrets.github_token }}
          reporter: github-pr-check
          level: error
          fail_on_error: false
          
